CREATE TABLE saneful_user (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    user_email TEXT,
    user_password TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);
