CREATE TABLE saneful_inventory (
    inventory_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    inventory_item1 TEXT NOT NULL,
    
   
    
    date_created TIMESTAMP DEFAULT now() NOT NULL
);
