CREATE TABLE saneful_store (
  item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_name TEXT NOT NULL,
  item_description TEXT,
  item_price INTEGER NOT NULL,
  is_unlimited BOOLEAN NOT NULL,
  item_available_qty INTEGER,
  can_use_anywhere BOOLEAN NOT NULL,
  use_at TEXT[]
);
